# CI/CD Pipeline
# This GitHub Actions workflow is responsible for deploying the expense_report application to an Oracle Compute Instance via SSH.
# It listens for push events on the main branch and triggers the deployment process.
# The workflow performs the following steps:
# 1. Checks out the code from the repository.
# 2. Logs in to DockerHub using the provided credentials.
# 3. Deploys the application to the Oracle Compute Instance by executing SSH commands.
#    - Stops any running containers.
#    - Prunes the Docker system to remove unused images and containers.
#    - Pulls the specified Docker image from DockerHub.
#    - Runs a new container with the pulled image, exposing port 8001.
#
# Environment Variables:
# - DOCKER_USERNAME: The username for DockerHub authentication.
# - DOCKER_PASSWORD: The password or access token for DockerHub authentication.
# - IMAGE_NAME: The name of the Docker image to deploy.
# - IMAGE_TAG: The tag of the Docker image to deploy.
#
# Secrets:
# - DOCKER_USERNAME: The DockerHub username stored as a secret in the GitHub repository.
# - DOCKERHUB_TOKEN: The DockerHub access token stored as a secret in the GitHub repository.
# - ORACLE_COMPUTE_HOST: The hostname or IP address of the Oracle Compute Instance stored as a secret in the GitHub repository.
# - ORACLE_COMPUTE_USERNAME: The username for SSH authentication to the Oracle Compute Instance stored as a secret in the GitHub repository.
# - ORACLE_COMPUTE_SSH_KEY: The private SSH key for authentication to the Oracle Compute Instance stored as a secret in the GitHub repository.


# name: CI/CD Pipeline

# on:
#   push:
#     branches: [ main ]

# env:
#   DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#   DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
#   IMAGE_NAME: tsmith4014/expense_report
#   IMAGE_TAG: letterhead  # Updated to use the existing tag on Docker Hub

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1

#     - name: Login to DockerHub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ env.DOCKER_USERNAME }}
#         password: ${{ env.DOCKER_PASSWORD }}

#     - name: Build and push Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         push: true
#         tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      
#     - run: echo "Build and push completed successfully."

#   deploy:
#     needs: build
#     runs-on: ubuntu-latest

#     steps:
#     - name: Deploy to Oracle Compute Instance via SSH
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.ORACLE_COMPUTE_HOST }}
#         username: ${{ secrets.ORACLE_COMPUTE_USERNAME }}
#         key: ${{ secrets.ORACLE_COMPUTE_SSH_KEY }}
#         script: |
#           echo "Starting deployment process..."
#           docker stop $(docker ps -q) || true
#           echo "Stopped all running containers."
#           docker system prune -a -f
#           echo "Pruned Docker system."
#           docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
#           echo "Pulled latest Docker image."
#           docker run -d -p 8001:80 ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
#           echo "Docker container started."

