#For some reason the github actions env is not able to build the image correctly, it builds the image and the container gets redeployed with the new image and the sites launches but when the user makes a form submission we get an error.  Something within the github env is not the same as my local env.  I will need to troubleshoot this issue.  but for now this works fine as a deployment pipeline.  I just have to build and push the image manually to dockerhub using buildex and docker push...docker buildx build --platform linux/amd64,linux/arm64 -t tsmith4014/expense_report:1.1 . --push

name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE_NAME: tsmith4014/expense_report
  IMAGE_TAG: mileage  # Updated to use the existing tag on Docker Hub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Deploy to Oracle Compute Instance via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ORACLE_COMPUTE_HOST }}
        username: ${{ secrets.ORACLE_COMPUTE_USERNAME }}
        key: ${{ secrets.ORACLE_COMPUTE_SSH_KEY }}
        script: |
          docker stop $(docker ps -q) || true
          docker system prune -a -f
          docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker run -d -p 8001:80 ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
