name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE_NAME: tsmith4014/expense_report
  IMAGE_TAG: 1.1  # Updated to use the existing tag on Docker Hub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Deploy to Oracle Compute Instance via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ORACLE_COMPUTE_HOST }}
        username: ${{ secrets.ORACLE_COMPUTE_USERNAME }}
        key: ${{ secrets.ORACLE_COMPUTE_SSH_KEY }}
        script: |
          docker stop $(docker ps -q) || true
          docker system prune -a -f
          docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker run -d -p 8001:80 ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
